/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Carts {
  cart_id: Generated<number>;
  created_at: Generated<Timestamp | null>;
  product_id: number;
  quantity: Generated<number>;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
  variant_id: number;
}

export interface Categories {
  category_id: Generated<number>;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  name: string;
  parent_id: number | null;
  updated_at: Generated<Timestamp | null>;
}

export interface Coupons {
  coupon_code: string;
  coupon_id: Generated<number>;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  discount_type: string;
  discount_value: Numeric;
  end_date: Timestamp;
  is_active: Generated<boolean | null>;
  max_discount_value: Numeric | null;
  min_order_value: Generated<Numeric | null>;
  start_date: Timestamp;
  updated_at: Generated<Timestamp | null>;
  usage_limit: Generated<number | null>;
}

export interface CouponUsages {
  coupon_id: number;
  id: Generated<number>;
  order_id: number;
  used_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface DrizzleDrizzleMigrations {
  created_at: Int8 | null;
  hash: string;
  id: Generated<number>;
}

export interface InterestType {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  interest_id: Generated<number>;
  interest_name: string;
  updated_at: Generated<Timestamp | null>;
}

export interface OrderItems {
  created_at: Generated<Timestamp | null>;
  order_id: number;
  order_item_id: Generated<number>;
  product_id: number;
  quantity: Generated<number>;
  sold_at_price: Numeric;
  updated_at: Generated<Timestamp | null>;
  variant_id: number;
}

export interface Orders {
  created_at: Generated<Timestamp | null>;
  order_date: Generated<Timestamp | null>;
  order_id: Generated<number>;
  shipping_address: Json;
  status: string | null;
  total_price: Numeric;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface Payments {
  amount: Numeric;
  created_at: Generated<Timestamp | null>;
  order_id: number;
  payment_id: Generated<number>;
  payment_method: string;
  status: Generated<string>;
  transaction_id: string | null;
  user_id: number;
}

export interface ProductInterestList {
  created_at: Generated<Timestamp | null>;
  interest_id: number;
  product_id: number;
  product_interest_list_id: Generated<number>;
  updated_at: Generated<Timestamp | null>;
}

export interface Products {
  base_price: Numeric;
  category_id: number;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  is_active: Generated<boolean | null>;
  name: string;
  product_id: Generated<number>;
  updated_at: Generated<Timestamp | null>;
  vendor_id: number | null;
}

export interface ProductSpecifications {
  attribute_name: string;
  attribute_value: string;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  product_id: number;
  spec_id: Generated<number>;
  updated_at: Generated<Timestamp | null>;
}

export interface ProductVariants {
  color: string | null;
  color_code: string | null;
  created_at: Generated<Timestamp | null>;
  dimensions: string | null;
  discount_amount: Numeric | null;
  discount_percentage: Numeric | null;
  in_stock: Generated<number | null>;
  price: Numeric;
  product_id: number;
  sku: string | null;
  updated_at: Generated<Timestamp | null>;
  variant_id: Generated<number>;
  weight_in_gm: Numeric | null;
}

export interface SavedAddresses {
  city: string;
  country: string;
  created_at: Generated<Timestamp | null>;
  house_number: string;
  latitude: Numeric;
  longitude: Numeric;
  saved_address_id: Generated<number>;
  state: string;
  street_name: string;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
  zip_code: string;
}

export interface UserInterestList {
  created_at: Generated<Timestamp | null>;
  interest_id: number;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
  user_interest_list_id: Generated<number>;
}

export interface Users {
  address: Json | null;
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  is_premium: Generated<boolean | null>;
  is_verified: Generated<boolean | null>;
  last_login: Generated<Timestamp | null>;
  name: string;
  password: string;
  updated_at: Generated<Timestamp | null>;
  user_type: string | null;
}

export interface VariantSpecifications {
  attribute_name: string;
  attribute_value: string;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  updated_at: Generated<Timestamp | null>;
  variant_id: number;
  variant_spec_id: Generated<number>;
}

export interface Vendor {
  created_at: Generated<Timestamp | null>;
  pin_code: string;
  type: string;
  updated_at: Generated<Timestamp | null>;
  vendor_address: string;
  vendor_gst_number: string;
  vendor_id: Generated<number>;
  vendor_latitude: Numeric;
  vendor_longitude: Numeric;
  vendor_name: string;
}

export interface Wishlists {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  updated_at: Generated<Timestamp | null>;
  users: number;
}

export interface DB {
  carts: Carts;
  categories: Categories;
  coupon_usages: CouponUsages;
  coupons: Coupons;
  "drizzle.__drizzle_migrations": DrizzleDrizzleMigrations;
  interest_type: InterestType;
  order_items: OrderItems;
  orders: Orders;
  payments: Payments;
  product_interest_list: ProductInterestList;
  product_specifications: ProductSpecifications;
  product_variants: ProductVariants;
  products: Products;
  saved_addresses: SavedAddresses;
  user_interest_list: UserInterestList;
  users: Users;
  variant_specifications: VariantSpecifications;
  vendor: Vendor;
  wishlists: Wishlists;
}
